### ISSUE TITLE
French parse not handling "." values

### ISSUE THREAD

**Issue by guilhermelabigalini** [BrightspaceUI/intl#61]
When I pass '-89.942,39' to the parser, I was expecting to get NaN, but it returns 89.

const d2lIntl = require('d2l-intl');

var parserFR = new d2lIntl.NumberParse('fr-CA');
console.log(parserFR.parse('-8 942,39')); // -> -8942.39
console.log(parserFR.parse('-89 942,39')); // -> -89942.39
console.log(parserFR.parse('-89942,39')); // -> -89942.39
console.log(parserFR.parse('-89.942,39')); // -> Expected NaN, but returns -89

**Comment by dlockhart** [comment]
Hi @guilhermelabigalini, thanks for submitting the issue.

This `intl` library is one we use internally for our own web application, so the logic isn't really standard. In fact, I'm not aware of a JavaScript standard for number parsing... only [number formatting](http://www.ecma-international.org/ecma-402/1.0/).

Currently it's just bailing out if it encounters any character it's not expecting -- `.` in this case. This may not be "correct", but at this time we don't plan to change it. The logic is trying its best to always return _something_, which again may not be always be correct but it's how our application and users have been using it for many years.

If you'd like it to behave differently, you're welcome to fork the repo or I'm sure there are many other Node.js-based number parsers.
